smd995/slowth

package.json
pnpm-lock.yaml
src/components/atom/progressBar/index.tsx

- progressBar 생성
- clsx, motion 설치했습니다.
- rawPercentage, percentage로 퍼센트 관련 변수 구분했습니다.
Closes #2

[feature] ProgressBar 컴포넌트 추가

---

src/components/atom/likeButton/index.tsx

- 좋아요버튼
- 애니메이션 처리
- 첫 렌더링 시에는 isLiked==true 여도 애니메이션 실행하지 않기 위해 버튼과의 상호작용 체크용 state변수 hasInteracted 를 만들어 사용했습니다.
Closes #12 
사용 예시 및 디자인은 노션 "공통 컴포넌트 설계 페이지" 참고

[feature] create LikeButton (찜하기 버튼) 

---

src/components/atom/modal/index.tsx
src/components/icons/CloseIcon.tsx

- Modal 컴포넌트 구조 설계 및 구현  
- 헤더/콘텐츠/푸터 구조 지원  
- isOpen, onClose, dimmer, size 등 props 설계  
- 접근성 대응 (role="dialog", aria-labelledby 등)  
- CloseIcon 컴포넌트로 분리하여 X 버튼 처리  
Closes #14
사용 예시 및 디자인은 노션 "공통 컴포넌트 설계 페이지" 참고

[feature] Modal 컴포넌트 구현

---

src/components/atom/infoChip/index.tsx

[feature] InfoChip 컴포넌트

---

src/components/atom/dropdown/index.tsx
src/components/icons/ArrowIcon.tsx
src/components/icons/DropdownIcons.tsx

- 리스트 or 모달 형태 지원 (openType)
- 아이콘 위치 및 종류 설정 가능
- 옵션 선택 시 값 반영 (selectBehavior: select/action)
- activeStyle, size props 추가
- 접근성 role, aria 적용
Closes #15
사용 예시 및 디자인은 노션 "공통 컴포넌트 설계 페이지" 참고

[feature] Dropdown 컴포넌트 구현

---

src/components/atom/chip/index.tsx

- label, selected, onClick, size props 처리
- 선택 여부에 따른 스타일 처리
- 사이즈에 따른 padding 스타일 처리
Closes #18
사용 예시 및 디자인은 노션 "공통 컴포넌트 설계 페이지" 참고

[feature] Chip 컴포넌트 구현

---

src/app/globals.css

작업 내용 
- typography 추가했습니다!
closes #37

chore: typography added (#37)

---

src/components/atom/Rating/index.tsx
src/components/molecules/gatheringInformation/index.spec.tsx
src/components/molecules/reviewItem/index.tsx
src/components/organisms/reveiwList/index.tsx
src/entity/review.ts

husky test 겸 rating 컴포넌트 color 수정만 올려보았습니다.

feature: reviewItem, reviewList 컴포넌트 구현 (#40)

---

src/components/atom/badge/index.tsx

- count props를 통한 숫자 렌더링 처리
- count가 0 이하일 경우 렌더링 생략
- 스타일: 높이 16px, 원형, 폰트 사이즈 및 색상 지정
Closes #50
- 공통 컴포넌트 설계 노션 참고

[feature] Badge 컴포넌트 구현 (#50)

---

__tests__/mocks/handler/user-handler.ts
package.json
pnpm-lock.yaml
src/app/(auth)/sign-up/page.tsx
src/components/atom/button/index.tsx
src/components/atom/input/index.tsx

- Button, Input 컴포넌트 리팩토링
- signup page 완성
Closes #64

feature: signup (#64)

---

src/app/globals.css
src/components/atom/likeButton/index.tsx
src/components/atom/rating/index.tsx
src/components/atom/ratingButton/index.tsx
src/components/molecules/gnb/index.tsx

- primary, secondary 색상 변경
- heart 색상 추가 및 관련 코드 수정
- GNB 컬러 수정
Closes #76

[style] global.css 컬러 변경 (#76)

---

__tests__/fixtures/user-fixture.ts
__tests__/mocks/handler/user-handler.ts
src/constants/test.ts
src/effect/auth/fetch-user/index.ts
src/effect/auth/sign-in/index.spec.ts
src/effect/auth/sign-in/index.ts
src/effect/auth/sign-up/index.spec.ts
src/entity/user.ts
src/types/env.d.ts
vitest.config.ts

- env 추가
- user handler 수정
- signin 함수 추가 및 테스트
Closes #66

[test] env 추가, user handler 수정, signin 함수 테스트

---

src/app/detail/[id]/page.tsx
src/components/molecules/gatheringInformation/index.spec.tsx

- detail/[id]/page.tsx 수정
- GatheringInformation test 코드 수정
Closes #80

fix: detail 오류 수정 (#80)

---

src/components/molecules/gatheringInformation/avatarList.tsx
src/components/organisms/ReviewsWithPagination/index.tsx

ReviewsWithPagination 의존성 배열 관련 수정
Closes #80

fix: ReviewsWithPagination 의존성 배열 관련 수정 (#80)

---

src/app/detail/[id]/layout.tsx
src/app/detail/[id]/not-found.tsx
src/app/detail/[id]/page.tsx
src/components/atom/likeButton/index.tsx
src/components/atom/openConfirmedBadge/index.tsx
src/components/atom/progressBar/index.tsx
src/components/molecules/gatheringInformation/index.tsx
src/effect/gatherings/getGatheringDetail.ts
src/effect/like/index.ts
src/effect/reviews/getReviews.ts

- getReveiws (리뷰목록조회 api 요청) 리팩토링
- 좋아요 액션 처리
- 모임 정보 찾을 수 없을 때 에러 처리 (404)
- not found (상세페이지용) 페이지
- progressBar 컬러 수정 및 기타 스타일 수정
Closes #85

[Refactor] detail 페이지 관련 리팩토링

---

src/components/atom/button/index.tsx
src/components/atom/input/index.tsx
src/components/organisms/loginForm/index.tsx
src/components/organisms/signUpForm/index.tsx

- forwardRef 삭제
- ref prop 추가
Closes #87

[refactor] button, input 컴포넌트 수정

---

src/app/GatheringListPage.tsx
src/components/molecules/calendar/index.tsx
src/components/molecules/filterBar/index.tsx
src/effect/gatherings/getGatheringList.ts

- 지역 필터링 기능 구현
- 날짜 필터링 기능 구현 (캘린더 초기화 시 전체 날짜 검색)
- 정렬 기준 변경 기능 구현
- 필터 변경 시 리스트 초기화 및 재조회
- 무한 스크롤 시 필터 조건 유지
- 날짜/시간 한국 시간(KST) 기준 표시
- 커스텀 캘린더 컴포넌트 구현
- 모임 리스트 key 중복 방지를 위해 id-index 조합으로 key 변경
Closes #113

[feature] 필터 기능 개선(지역, 날짜, 정렬) 및 캘린더 컴포넌트 구현

---

src/app/GatheringListPage.tsx
src/components/atom/dropdown/index.tsx
src/components/molecules/calendar/index.tsx
src/components/molecules/filterBar/index.tsx
src/components/molecules/gatheringCard/index.tsx
src/components/molecules/gnb/index.tsx

- Dropdown: 선택 시 아이콘 색상 반영, activeStyle 로직 개선
- Dropdown: select/action 모드 분기, 외부 클릭 시 닫힘 처리
- Calendar: 날짜 선택 후 '적용' 시에만 필터 적용, 초기화 버튼 추가
- Calendar: 외부 클릭 시 미적용 값 롤백 처리
- FilterBar: Calendar 연동 필터 로직 수정, 날짜 초기화 처리
- GatheringListPage: 필터 적용 및 초기화 흐름 리팩토링
Closes #124

[refactor] Dropdown, Calendar, FilterBar 개선 및 버그 수정 (#124)

---

src/app/globals.css
src/app/page.tsx
src/components/atom/timeColumn/index.tsx
src/components/molecules/calendar/index.tsx
src/components/molecules/calendarBody/index.tsx
src/components/molecules/filterBar/index.tsx
src/components/molecules/gatheringListPage/index.tsx

- 기존 Calendar 컴포넌트의 코드 복잡도를 낮추고 유지보수를 용이하게 하기 위해 리팩토링을 진행합니다.
- 기존 코드에 존재하는 하드코딩, 중복, 불명확한 네이밍 등을 개선합니다.
- Calendar 컴포넌트 Day.js 기반으로 리팩토링
- 시간, 분 항목 생성 코드 최적화
- 날짜 선택 시 div → button 요소로 변경 (접근성 개선)
- 하드코딩된 월/요일 배열 → Day.js 기반 포맷팅
- Magic Number 상수화
Closes #140 
- GatheringListPage 폴더 이동 및 import 경로 수정
- 모든 button 요소에 cursor-pointer 적용 (UX 개선)
- 모임 만들기 모달에서 사용되는 datetime 모드는 개발 진행중

[refactor] Calendar 컴포넌트 리팩토링 및 코드 구조 개선 (#140)

---

src/components/molecules/gatheringCard/index.tsx
src/effect/gatherings/getGatheringList.ts

- `getGatheringList` API URL 및 TEAM ID 환경변수화
- `Image` 컴포넌트에 `sizes` 속성 추가
- `Image` 컴포넌트에 `priority` 속성 추가

[refactor] API 환경변수 적용 및 이미지 최적화 (#146)

---

src/components/organisms/gatheringModal/index.tsx
src/libs/date/getLocalizedDate.ts
src/libs/date/getUTCDate.spec.ts
src/libs/date/getUTCDate.ts

- 날짜 전송 시 변경하여 전송
- getUTCDate 함수 생성
Closes #145

fix: gatheringModal formatted date fixed (#145)

---

src/components/atom/fileInput/index.tsx
src/components/organisms/gatheringModal/index.tsx
src/effect/gatherings/createGathering.ts

- 파일 입력 유틸 개선
- 토스트 추가
- 제출시 닫힘 추가
Closes #136

refactor: gatheringModal api  fileInput edited (#136)

---

src/components/molecules/createdGatherings/index.tsx
src/components/molecules/horizontalMyGatheringCard/index.tsx
src/components/molecules/myGatherings/index.tsx
src/components/molecules/tabContent/index.tsx
src/components/molecules/verticalMyGatheringCard/index.tsx
src/effect/gatherings/getCreatedGatherings.ts
src/effect/gatherings/getMyGatherings.ts
src/stores/gatheringStore.ts

- getMyGatherings api 호출 함수 구현
- 모 취소하기 api 호출 함수 구현
Closes #171

feature: mypage-myGatherings (#171)

---

src/app/(detail)/gathering/[id]/page.tsx
src/components/molecules/gatheringInformation/participantInfo.tsx
src/components/organisms/gatheringDetailPage/index.tsx
src/components/skeleton/GatheringDetailSkeleton.tsx

- 이미지 최적화
> Lighthouse로 성능 검사 시, 상세페이지의 이미지 부분에서 LCP가 높게 나옴을 확인했습니다.
> 이를 해결하기 위해 서버컴포넌트 단계에서 이미지를 preload 하는 코드를 추가하였습니다.
- 모집 정원 숫자 올라가는 애니메이션 추가
Closes #173

refactor: detail (#173)

---

src/components/atom/customDateTime/index.tsx
src/components/atom/customSelect/index.tsx
src/components/atom/fileInput/index.tsx
src/components/atom/input/index.tsx
src/components/atom/select/index.tsx
src/components/organisms/createGatheringModalUI/index.tsx

refactor: createGatheringModalUI-refactoring (#192)

---

src/effect/auth/index.ts
src/effect/gatherings/cancelGathering.ts
src/effect/gatherings/createGathering.ts
src/effect/gatherings/getCreatedGatherings.ts
src/effect/gatherings/getGatheringListCSR.ts
src/effect/gatherings/getJoinedGatherings.ts
src/effect/gatherings/getMyGatherings.ts
src/effect/gatherings/joinGathering.ts
src/effect/gatherings/leaveGathering.ts
src/effect/reviews/createReview.ts
src/effect/user/index.ts
src/shared/api/client.ts
src/shared/api/index.ts
src/shared/api/types.ts
src/shared/lib/date/get-deadline-message.ts
src/shared/lib/date/get-formatted-date.ts
src/shared/lib/date/get-localized-date.ts
src/shared/lib/date/get-utc-date.ts
src/shared/lib/date/index.ts
src/shared/lib/date/is-past-now.ts
src/shared/lib/format-score-summary.ts
src/shared/lib/index.ts

- feat(shared): API 클라이언트를 shared/api로 이동
- refactor: TypeScript 경로 매핑 업데이트
Closes #209

[refactor] shared-api
